#Requires -Modules ActiveDirectory
<#
.SYNOPSIS
    FSMO Role Manager - List, Test, Recommend, Move, and Validate FSMO Roles

.DESCRIPTION
    Interactive script to:
      1. List all FSMO roles and their current holders
      2. Test AD health (replication, connectivity, services)
      3. Recommend the best target DC for FSMO roles
      4. Let the user pick the target server
      5. Move FSMO roles
      6. Post-move validation + save full log to user's Desktop

.NOTES
    Run as Domain Admin on a Domain Controller or machine with RSAT installed.
    Author  : Generated by Claude
    Version : 1.1 – Fixed replication check false positives (now uses Get-ADReplicationPartnerMetadata)
#>

# ─────────────────────────────────────────────────────────────────────────────
# REGION: Initialization
# ─────────────────────────────────────────────────────────────────────────────
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Log array – everything written here is also saved to the desktop at the end
$Script:Log = [System.Collections.Generic.List[string]]::new()

function Write-Log {
    param(
        [string]$Message,
        [ValidateSet("INFO","WARN","ERROR","SUCCESS","HEADER")]
        [string]$Level = "INFO"
    )
    $ts        = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logLine   = "[$ts][$Level] $Message"
    $Script:Log.Add($logLine)

    $color = switch ($Level) {
        "INFO"    { "Cyan"    }
        "WARN"    { "Yellow"  }
        "ERROR"   { "Red"     }
        "SUCCESS" { "Green"   }
        "HEADER"  { "Magenta" }
    }
    Write-Host $logLine -ForegroundColor $color
}

function Save-Log {
    $desktop  = [Environment]::GetFolderPath("Desktop")
    $stamp    = Get-Date -Format "yyyyMMdd_HHmmss"
    $logFile  = Join-Path $desktop "FSMO_Move_Log_$stamp.txt"
    $Script:Log | Out-File -FilePath $logFile -Encoding UTF8
    Write-Host "`nLog saved to: $logFile" -ForegroundColor Green
    return $logFile
}

function Show-Banner {
    Clear-Host
    Write-Host ("=" * 70) -ForegroundColor Magenta
    Write-Host "          FSMO Role Manager – Interactive PowerShell Tool" -ForegroundColor White
    Write-Host ("=" * 70) -ForegroundColor Magenta
    Write-Host ""
}

# ─────────────────────────────────────────────────────────────────────────────
# REGION: 1 – List FSMO Roles
# ─────────────────────────────────────────────────────────────────────────────
function Get-FSMORoles {
    Write-Log "Retrieving FSMO role holders..." "HEADER"

    $forest = Get-ADForest
    $domain = Get-ADDomain

    $roles = [ordered]@{
        "Schema Master"          = $forest.SchemaMaster
        "Domain Naming Master"   = $forest.DomainNamingMaster
        "PDC Emulator"           = $domain.PDCEmulator
        "RID Master"             = $domain.RIDMaster
        "Infrastructure Master"  = $domain.InfrastructureMaster
    }

    Write-Host ""
    Write-Host ("{0,-30} {1}" -f "FSMO Role", "Current Holder") -ForegroundColor White
    Write-Host ("{0,-30} {1}" -f ("-"*29), ("-"*39)) -ForegroundColor Gray

    foreach ($role in $roles.GetEnumerator()) {
        Write-Host ("{0,-30} {1}" -f $role.Key, $role.Value) -ForegroundColor Cyan
        Write-Log "$($role.Key) = $($role.Value)"
    }
    Write-Host ""
    return $roles
}

# ─────────────────────────────────────────────────────────────────────────────
# REGION: 2 – AD Health Tests
# ─────────────────────────────────────────────────────────────────────────────
function Test-ADHealth {
    param([string[]]$DCList)

    Write-Log "─── Starting AD Health Tests ───" "HEADER"
    $results = @{}

    foreach ($dc in $DCList) {
        Write-Log "Testing DC: $dc" "INFO"
        $dcResult = [ordered]@{
            DC              = $dc
            Ping            = $false
            LDAPPort        = $false
            KerberosPort    = $false
            NetlogonService = $false
            KDCService      = $false
            ADWSService     = $false
            ReplicationOK   = $false
            ReplicationErrors = 0
            SysvolPresent   = $false
            Score           = 0
        }

        # Ping
        try {
            $ping = Test-Connection -ComputerName $dc -Count 2 -Quiet
            $dcResult.Ping = $ping
            if ($ping) { Write-Log "  [PASS] Ping $dc" "SUCCESS" }
            else        { Write-Log "  [FAIL] Ping $dc" "WARN"    }
        } catch { Write-Log "  [ERROR] Ping $dc : $_" "ERROR" }

        # LDAP port 389
        try {
            $tcp = Test-NetConnection -ComputerName $dc -Port 389 -WarningAction SilentlyContinue
            $dcResult.LDAPPort = $tcp.TcpTestSucceeded
            $status = if ($tcp.TcpTestSucceeded) {"PASS"} else {"FAIL"}
            Write-Log "  [$status] LDAP (389) $dc" $(if($status -eq "PASS"){"SUCCESS"}else{"WARN"})
        } catch { Write-Log "  [ERROR] LDAP test $dc : $_" "ERROR" }

        # Kerberos port 88
        try {
            $tcp = Test-NetConnection -ComputerName $dc -Port 88 -WarningAction SilentlyContinue
            $dcResult.KerberosPort = $tcp.TcpTestSucceeded
            $status = if ($tcp.TcpTestSucceeded) {"PASS"} else {"FAIL"}
            Write-Log "  [$status] Kerberos (88) $dc" $(if($status -eq "PASS"){"SUCCESS"}else{"WARN"})
        } catch { Write-Log "  [ERROR] Kerberos test $dc : $_" "ERROR" }

        # Windows Services
        foreach ($svc in @("Netlogon","Kdc","ADWS")) {
            try {
                $s = Get-Service -ComputerName $dc -Name $svc -ErrorAction Stop
                $running = ($s.Status -eq "Running")
                $dcResult["${svc}Service"] = $running
                $status = if ($running) {"PASS"} else {"FAIL"}
                Write-Log "  [$status] Service $svc on $dc" $(if($status -eq "PASS"){"SUCCESS"}else{"WARN"})
            } catch {
                Write-Log "  [WARN] Cannot query service $svc on $dc : $_" "WARN"
            }
        }

        # AD Replication — uses Get-ADReplicationPartnerMetadata (authoritative, no false positives)
        try {
            $replMeta   = @(Get-ADReplicationPartnerMetadata -Target $dc -ErrorAction Stop)
            $replErrors = @($replMeta | Where-Object {
                $_.ConsecutiveReplicationFailures -gt 0 -or $_.LastReplicationResult -ne 0
            }).Count
            $replOK = ($replErrors -eq 0)
            $dcResult.ReplicationOK     = $replOK
            $dcResult.ReplicationErrors = $replErrors
            $status = if ($replOK) {"PASS"} else {"WARN"}
            Write-Log "  [$status] Replication $dc (consecutive failures: $replErrors)" $(if($replOK){"SUCCESS"}else{"WARN"})
        } catch { Write-Log "  [WARN] Replication check failed for $dc : $_" "WARN" }

        # SYSVOL share
        try {
            $sysvol = Test-Path "\\$dc\SYSVOL"
            $dcResult.SysvolPresent = $sysvol
            $status = if ($sysvol) {"PASS"} else {"FAIL"}
            Write-Log "  [$status] SYSVOL share on $dc" $(if($status -eq "PASS"){"SUCCESS"}else{"WARN"})
        } catch { Write-Log "  [WARN] SYSVOL check failed for $dc : $_" "WARN" }

        # Score (1 point per passing check)
        $checks = @("Ping","LDAPPort","KerberosPort","NetlogonService","KdcService","ADWSService","ReplicationOK","SysvolPresent")
        $dcResult.Score = ($checks | Where-Object { $dcResult[$_] -eq $true }).Count

        $results[$dc] = $dcResult
    }

    return $results
}

# ─────────────────────────────────────────────────────────────────────────────
# REGION: 3 – Recommend Target DC
# ─────────────────────────────────────────────────────────────────────────────
function Get-Recommendation {
    param(
        [hashtable]$HealthResults,
        [hashtable]$CurrentRoles
    )

    Write-Log "─── Generating Recommendation ───" "HEADER"

    # Exclude current FSMO holders from candidates to avoid a no-op
    $currentHolders = $CurrentRoles.Values | ForEach-Object { $_.Split(".")[0].ToUpper() }

    $ranked = $HealthResults.GetEnumerator() |
        Sort-Object { $_.Value.Score } -Descending

    Write-Host ""
    Write-Host ("{0,-35} {1,-8} {2}" -f "Domain Controller", "Score", "Notes") -ForegroundColor White
    Write-Host ("{0,-35} {1,-8} {2}" -f ("-"*34),("-"*7),("-"*30)) -ForegroundColor Gray

    $recommended = $null
    foreach ($entry in $ranked) {
        $dc    = $entry.Key
        $score = $entry.Value.Score
        $note  = if ($currentHolders -contains $dc.Split(".")[0].ToUpper()) { "(current FSMO holder)" } else { "" }
        $color = if ($score -ge 7) { "Green" } elseif ($score -ge 4) { "Yellow" } else { "Red" }
        Write-Host ("{0,-35} {1,-8} {2}" -f $dc, "$score/8", $note) -ForegroundColor $color
        Write-Log "Ranked: $dc Score=$score/8 $note"

        if (-not $recommended -and $note -eq "") {
            $recommended = $dc
        }
    }

    Write-Host ""
    if ($recommended) {
        Write-Host "  ★  Recommended target: $recommended (highest health score among non-current holders)" -ForegroundColor Green
        Write-Log "Recommendation: $recommended" "SUCCESS"
    } else {
        Write-Host "  ⚠  Could not find a non-FSMO-holder DC with good health. Review manually." -ForegroundColor Yellow
        Write-Log "No clear recommendation available." "WARN"
    }

    return $recommended
}

# ─────────────────────────────────────────────────────────────────────────────
# REGION: 4 – User Picks Target Server
# ─────────────────────────────────────────────────────────────────────────────
function Select-TargetDC {
    param(
        [string[]]$DCList,
        [string]$Recommended
    )

    Write-Host ""
    Write-Host "Available Domain Controllers:" -ForegroundColor White
    for ($i = 0; $i -lt $DCList.Count; $i++) {
        $tag = if ($DCList[$i] -eq $Recommended) { " ← Recommended" } else { "" }
        Write-Host "  [$($i+1)] $($DCList[$i])$tag" -ForegroundColor Cyan
    }

    Write-Host ""
    do {
        $choice = Read-Host "Enter the number of the TARGET DC for FSMO roles (or 'Q' to quit)"
        if ($choice -eq 'Q') { Write-Log "User chose to quit." "WARN"; Save-Log; exit }
        $idx = [int]$choice - 1
    } until ($idx -ge 0 -and $idx -lt $DCList.Count)

    $selected = $DCList[$idx]
    Write-Log "User selected target DC: $selected" "INFO"
    Write-Host ""
    Write-Host "  Selected: $selected" -ForegroundColor Green

    # Confirm
    $confirm = Read-Host "Confirm move of ALL FSMO roles to '$selected'? (Y/N)"
    if ($confirm -notmatch '^[Yy]') {
        Write-Log "User cancelled the move." "WARN"
        Write-Host "Operation cancelled." -ForegroundColor Yellow
        Save-Log
        exit
    }

    return $selected
}

# ─────────────────────────────────────────────────────────────────────────────
# REGION: 5 – Move FSMO Roles
# ─────────────────────────────────────────────────────────────────────────────
function Move-FSMORoles {
    param([string]$TargetDC)

    Write-Log "─── Moving FSMO Roles to $TargetDC ───" "HEADER"

    $rolesToMove = @(
        "SchemaMaster",
        "DomainNamingMaster",
        "PDCEmulator",
        "RIDMaster",
        "InfrastructureMaster"
    )

    $moved        = @()
    $failed       = @()
    $CleanTarget  = $TargetDC.Trim()
    $ShortTarget  = $CleanTarget.Split('.')[0]

    foreach ($role in $rolesToMove) {
        $roleOK = $false

        # Attempt 1 – FQDN with -Server pointed directly at target DC
        try {
            Write-Log "Moving $role → $CleanTarget (FQDN) ..." "INFO"
            Move-ADDirectoryServerOperationMasterRole `
                -Identity $CleanTarget `
                -OperationMasterRole $role `
                -Server $CleanTarget `
                -Force `
                -Confirm:$false `
                -ErrorAction Stop
            Write-Log "  [OK] $role moved successfully." "SUCCESS"
            $moved += $role
            $roleOK = $true
        } catch {
            Write-Log "  [RETRY] FQDN attempt failed for $role — trying short name: $ShortTarget" "WARN"
        }

        # Attempt 2 – Short name fallback
        if (-not $roleOK) {
            try {
                Move-ADDirectoryServerOperationMasterRole `
                    -Identity $ShortTarget `
                    -OperationMasterRole $role `
                    -Server $ShortTarget `
                    -Force `
                    -Confirm:$false `
                    -ErrorAction Stop
                Write-Log "  [OK] $role moved via short name ($ShortTarget)." "SUCCESS"
                $moved += $role
                $roleOK = $true
            } catch {
                Write-Log "  [ERROR] Failed to move ${role}: $($_.Exception.Message)" "ERROR"
                $failed += $role
            }
        }
    }

    Write-Host ""
    Write-Host "  Moved  : $($moved -join ', ')" -ForegroundColor Green
    if ($failed) {
        Write-Host "  Failed : $($failed -join ', ')" -ForegroundColor Red
    }

    return @{ Moved = $moved; Failed = $failed }
}

# ─────────────────────────────────────────────────────────────────────────────
# REGION: 6 – Post-Move Validation
# ─────────────────────────────────────────────────────────────────────────────
function Confirm-FSMOMoveSuccess {
    param(
        [string]$ExpectedDC,
        [hashtable]$MoveResult
    )

    Write-Log "─── Post-Move Validation ───" "HEADER"
    Start-Sleep -Seconds 5   # Allow AD to propagate

    $forest = Get-ADForest
    $domain = Get-ADDomain

    $newRoles = [ordered]@{
        "Schema Master"         = $forest.SchemaMaster
        "Domain Naming Master"  = $forest.DomainNamingMaster
        "PDC Emulator"          = $domain.PDCEmulator
        "RID Master"            = $domain.RIDMaster
        "Infrastructure Master" = $domain.InfrastructureMaster
    }

    Write-Host ""
    Write-Host ("{0,-30} {1,-35} {2}" -f "FSMO Role","New Holder","Status") -ForegroundColor White
    Write-Host ("{0,-30} {1,-35} {2}" -f ("-"*29),("-"*34),("-"*10)) -ForegroundColor Gray

    $allOK = $true
    foreach ($role in $newRoles.GetEnumerator()) {
        $holder = $role.Value
        $ok     = $holder -like "$ExpectedDC*"
        $status = if ($ok) { "✔ OK" } else { "✘ MISMATCH" }
        $color  = if ($ok) { "Green" } else { "Red" }
        Write-Host ("{0,-30} {1,-35} {2}" -f $role.Key, $holder, $status) -ForegroundColor $color
        Write-Log "POST-MOVE: $($role.Key) = $holder [$status]" $(if($ok){"SUCCESS"}else{"ERROR"})
        if (-not $ok) { $allOK = $false }
    }

    Write-Host ""
    if ($allOK) {
        Write-Log "All FSMO roles successfully verified on $ExpectedDC." "SUCCESS"
        Write-Host "  ★ All FSMO roles confirmed on $ExpectedDC" -ForegroundColor Green
    } else {
        Write-Log "One or more FSMO roles did NOT move as expected." "ERROR"
        Write-Host "  ⚠ Some roles may not have moved. Review the log." -ForegroundColor Red
    }

    return $allOK
}

# ─────────────────────────────────────────────────────────────────────────────
# MAIN EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
Show-Banner

# ── Step 1: List FSMO roles ──────────────────────────────────────────────────
Write-Host "STEP 1 – Current FSMO Role Holders" -ForegroundColor Magenta
Write-Host ("─" * 50) -ForegroundColor Gray
$currentRoles = Get-FSMORoles

# ── Pause: Let user review roles before proceeding ───────────────────────────
Write-Host ""
Write-Host "  Do you want to continue and move the FSMO roles?" -ForegroundColor Yellow
$proceed = Read-Host "  Press ENTER to continue or type 'Q' to quit"
if ($proceed -match '^[Qq]') {
    Write-Log "User chose to exit after reviewing FSMO roles. No changes made." "WARN"
    Write-Host ""
    Write-Host "  Exiting. No changes were made." -ForegroundColor Yellow
    Save-Log
    exit
}
Write-Host ""

# ── Step 2: Discover all DCs ─────────────────────────────────────────────────
Write-Host "STEP 2 – Discovering Domain Controllers" -ForegroundColor Magenta
Write-Host ("─" * 50) -ForegroundColor Gray
$allDCs = (Get-ADDomainController -Filter *).HostName
Write-Log "Found $($allDCs.Count) domain controller(s): $($allDCs -join ', ')"
Write-Host "  Found: $($allDCs -join ', ')" -ForegroundColor Cyan
Write-Host ""

# ── Step 3: Health Tests ─────────────────────────────────────────────────────
Write-Host "STEP 3 – AD Health Tests" -ForegroundColor Magenta
Write-Host ("─" * 50) -ForegroundColor Gray
$healthResults = Test-ADHealth -DCList $allDCs
Write-Host ""

# ── Step 4: Recommend ────────────────────────────────────────────────────────
Write-Host "STEP 4 – Recommendation" -ForegroundColor Magenta
Write-Host ("─" * 50) -ForegroundColor Gray
$recommended = Get-Recommendation -HealthResults $healthResults -CurrentRoles $currentRoles
Write-Host ""

# ── Step 5: User Selects Target ──────────────────────────────────────────────
Write-Host "STEP 5 – Select Target DC" -ForegroundColor Magenta
Write-Host ("─" * 50) -ForegroundColor Gray
$targetDC = Select-TargetDC -DCList $allDCs -Recommended $recommended

# ── Step 6: Move Roles ───────────────────────────────────────────────────────
Write-Host ""
Write-Host "STEP 6 – Moving FSMO Roles" -ForegroundColor Magenta
Write-Host ("─" * 50) -ForegroundColor Gray
$moveResult = Move-FSMORoles -TargetDC $targetDC

# ── Step 7: Post-Move Validation ─────────────────────────────────────────────
Write-Host ""
Write-Host "STEP 7 – Post-Move Validation" -ForegroundColor Magenta
Write-Host ("─" * 50) -ForegroundColor Gray
$success = Confirm-FSMOMoveSuccess -ExpectedDC $targetDC -MoveResult $moveResult

# ── Step 8: Save Log ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "STEP 8 – Saving Log" -ForegroundColor Magenta
Write-Host ("─" * 50) -ForegroundColor Gray
$logPath = Save-Log

Write-Host ""
Write-Host ("=" * 70) -ForegroundColor Magenta
Write-Host "  FSMO Move Operation Complete" -ForegroundColor White
Write-Host "  Log saved to: $logPath" -ForegroundColor Cyan
Write-Host ("=" * 70) -ForegroundColor Magenta
